name: 'Validate Organization Membership'
description: 'Validates that a user is a member of the organization'
inputs:
  github-token:
    description: 'GitHub token with organization member read permissions'
    required: true
  username:
    description: 'Username to validate'
    required: true
  org:
    description: 'Organization name'
    required: true
outputs:
  status:
    description: 'Validation status: "valid" (member found), "invalid" (404 - not a member), or "error" (other API errors)'
    value: ${{ steps.validate.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Validate membership
      id: validate
      uses: actions/github-script@v7
      env:
        USERNAME_JSON: ${{ toJSON(inputs.username) }}
        ORG_JSON: ${{ toJSON(inputs.org) }}
      with:
        github-token: ${{ inputs.github-token }}
        result-encoding: string
        script: |
          const username = JSON.parse(process.env.USERNAME_JSON);
          const org = JSON.parse(process.env.ORG_JSON);
          
          console.log(`Validating org membership for: ${username}`);

          try {
            await github.rest.orgs.getMembershipForUser({
              org: org,
              username: username
            });
            console.log(`${username} is a valid org member`);
            return 'valid';
          } catch (error) {
            if (error?.status === 404) {
              console.error(`${username} is not an org member`);
              return 'invalid';
            }

            console.error(`Error while checking org membership for ${username}:`, error);
            return 'error';
          }
