name: 'Remove Issue Label'
description: 'Removes a label from an issue with error handling for missing labels'
inputs:
  github-token:
    description: 'GitHub token with issues write permissions'
    required: true
  label-name:
    description: 'Name of the label to remove'
    required: true
  issue-number:
    description: 'Issue number'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Remove label
      uses: actions/github-script@v7
      env:
        LABEL_NAME_JSON: ${{ toJSON(inputs.label-name) }}
        ISSUE_NUMBER_JSON: ${{ toJSON(inputs.issue-number) }}
        OWNER_JSON: ${{ toJSON(inputs.owner) }}
        REPO_JSON: ${{ toJSON(inputs.repo) }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const labelName = JSON.parse(process.env.LABEL_NAME_JSON);
          const issueNumber = Number(JSON.parse(process.env.ISSUE_NUMBER_JSON));
          const owner = JSON.parse(process.env.OWNER_JSON);
          const repo = JSON.parse(process.env.REPO_JSON);
          
          await github.rest.issues.removeLabel({
            owner: owner,
            repo: repo,
            issue_number: issueNumber,
            name: labelName
          }).catch(error => {
            if (error && error.status === 404) {
              console.warn(`Label "${labelName}" not found when attempting removal; nothing to remove.`);
              return;
            }
            // Rethrow unexpected errors so the workflow can fail and surface the issue.
            throw error;
          });
